# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Flutter Project

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gatorfit_flutter

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: dart test

      - name: flutter-android-build
      # You may pin to the exact commit or the version.
      # uses: NiklasLehnfeld/flutter-android-build-action@cccda64e2121a75201ca0299974cf4611610e99b
        uses: ./.github/actions/
        with:
          working-directory: ./gatorfit_flutter
          action: NiklasLehnfeld/flutter-android-build-action@v2
          action-parameters: '{"release" : false, "build-type" : "both"}'
          # If set to `true`, it will run release builds, otherwise debug builds
          # release: false
          # apk | aab | both
          # build-type: both
          # Base64 encoded keystore.jks, required if release is true
          # keystore: # optional
          # default is keystore password, required if release is true
          # keystore-pwd: # optional, 
          # default is key password, required if release is true
          # key-pwd: # optional, default is 
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ${{ steps.android-build.outputs.apk-path }}
      - name: Archive AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: ${{ steps.android-build.outputs.aab-path }}
                
